import jsPDF from "jspdf";

export function downloadTextAsPdf(title: string, body: string) {
  const doc = new jsPDF({ unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 40;
  const maxW = pageW - margin * 2;

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  const titleLines = doc.splitTextToSize(title || "Nova AI Notes", maxW);
  doc.text(titleLines, margin, margin + 10);

  let y = margin + 10 + titleLines.length * 20 + 10;

  // Subtitle
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(120);
  doc.text(
    `Generated by Nova AI · ${new Date().toLocaleString()}`,
    margin,
    y
  );
  y += 18;

  // Body — strip basic markdown for cleaner PDF
  const clean = body
    .replace(/```[\s\S]*?```/g, (m) => m.replace(/```/g, ""))
    .replace(/[*_`#>]/g, "")
    .replace(/\[(.*?)\]\((.*?)\)/g, "$1 ($2)");

  doc.setTextColor(20);
  doc.setFontSize(11);
  const lines = doc.splitTextToSize(clean, maxW);
  const lineH = 15;
  for (const line of lines) {
    if (y + lineH > pageH - margin) {
      doc.addPage();
      y = margin;
    }
    doc.text(line, margin, y);
    y += lineH;
  }

  const safe = (title || "nova-notes")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 60);
  doc.save(`${safe || "nova-notes"}.pdf`);
}
