import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { FileText, Loader2, Sparkles, Download, Bookmark } from "lucide-react";
import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { AppHeader } from "@/components/app-header";
import { useProfile, EXAMS, type ExamKey } from "@/hooks/use-profile";
import { useBookmarks } from "@/hooks/use-bookmarks";
import { toast } from "sonner";

export const Route = createFileRoute("/papers")({
  head: () => ({
    meta: [
      { title: "Question Papers — Nova AI" },
      {
        name: "description",
        content:
          "Previous year papers and AI-generated mock papers with one-click PDF export.",
      },
    ],
  }),
  component: PapersPage,
});

type Question = {
  question: string;
  type: "mcq" | "short" | "long";
  options?: string[];
  answer: string;
  explanation?: string;
  marks?: number;
};

type Paper = { title: string; questions: Question[] };

function PapersPage() {
  const [profile] = useProfile();
  const [exam, setExam] = useState<ExamKey>(profile.exam ?? "JEE");
  const [topic, setTopic] = useState("");
  const [count, setCount] = useState(10);
  const [type, setType] = useState<"mcq" | "mixed" | "short">("mcq");
  const [loading, setLoading] = useState(false);
  const [paper, setPaper] = useState<Paper | null>(null);
  const [showAnswers, setShowAnswers] = useState(false);
  const { add } = useBookmarks();

  const generate = async () => {
    if (!topic.trim()) {
      toast.error("Topic ya chapter daalo");
      return;
    }
    setLoading(true);
    setPaper(null);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          kind: "questions",
          prompt: `Generate ${count} ${
            type === "mixed" ? "mixed (MCQs + short + long)" : type.toUpperCase()
          } questions for ${exam} exam on the topic "${topic}". Include accurate answers and brief explanations. Match the actual ${exam} difficulty and pattern. Use realistic numerical values for physics/chemistry/maths. Title should be like "${exam} Mock — ${topic}".`,
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      const data = (await res.json()) as Paper;
      setPaper(data);
    } catch (e) {
      console.error(e);
      toast.error("Generation failed", {
        description: e instanceof Error ? e.message : "Try again",
      });
    } finally {
      setLoading(false);
    }
  };

  const downloadPdf = async () => {
    if (!paper) return;
    const doc = await PDFDocument.create();
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const fontBold = await doc.embedFont(StandardFonts.HelveticaBold);

    const PAGE_W = 595;
    const PAGE_H = 842;
    const M = 50;
    let page = doc.addPage([PAGE_W, PAGE_H]);
    let y = PAGE_H - M;

    const wrap = (text: string, size: number, f = font, maxW = PAGE_W - 2 * M) => {
      const words = text.split(/\s+/);
      const lines: string[] = [];
      let line = "";
      for (const w of words) {
        const test = line ? line + " " + w : w;
        const width = f.widthOfTextAtSize(test, size);
        if (width > maxW) {
          if (line) lines.push(line);
          line = w;
        } else {
          line = test;
        }
      }
      if (line) lines.push(line);
      return lines;
    };

    const draw = (text: string, size: number, f = font, color = rgb(0, 0, 0)) => {
      const lines = wrap(text, size, f);
      for (const l of lines) {
        if (y < M + size + 4) {
          page = doc.addPage([PAGE_W, PAGE_H]);
          y = PAGE_H - M;
        }
        page.drawText(l, { x: M, y, size, font: f, color });
        y -= size + 4;
      }
    };

    draw(paper.title, 18, fontBold, rgb(0.4, 0.2, 0.7));
    y -= 6;
    draw(`Generated by Nova AI · by REHAN SHAIKH`, 9, font, rgb(0.4, 0.4, 0.4));
    y -= 10;

    paper.questions.forEach((q, i) => {
      y -= 8;
      draw(`Q${i + 1}. ${q.question}`, 11, fontBold);
      if (q.options && q.options.length) {
        q.options.forEach((o, idx) => {
          draw(`   ${String.fromCharCode(65 + idx)}) ${o}`, 10);
        });
      }
      if (q.marks) draw(`   [${q.marks} marks]`, 9, font, rgb(0.4, 0.4, 0.4));
    });

    // Answer key
    page = doc.addPage([PAGE_W, PAGE_H]);
    y = PAGE_H - M;
    draw("Answer Key & Explanations", 16, fontBold, rgb(0.4, 0.2, 0.7));
    y -= 6;
    paper.questions.forEach((q, i) => {
      y -= 6;
      draw(`Q${i + 1}. ${q.answer}`, 10, fontBold);
      if (q.explanation) draw(q.explanation, 9, font, rgb(0.3, 0.3, 0.3));
    });

    const bytes = await doc.save();
    const blob = new Blob([bytes as BlobPart], { type: "application/pdf" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${paper.title.replace(/[^a-z0-9]+/gi, "_")}.pdf`;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("PDF downloaded");
  };

  return (
    <div>
      <AppHeader title="Question Papers" subtitle="AI mock generator + PDF" />

      <div className="glass mb-3 rounded-2xl p-3 space-y-3">
        <div>
          <label className="text-[10px] uppercase tracking-wider text-muted-foreground">
            Exam
          </label>
          <div className="mt-1.5 flex gap-1.5 overflow-x-auto pb-1 -mx-1 px-1">
            {EXAMS.map((e) => (
              <button
                key={e.key}
                onClick={() => setExam(e.key)}
                className={`shrink-0 rounded-lg border px-2.5 py-1.5 text-[11px] ${
                  exam === e.key
                    ? "border-primary/60 bg-primary/15 text-foreground"
                    : "border-white/10 bg-white/5 text-muted-foreground"
                }`}
              >
                {e.emoji} {e.key}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="text-[10px] uppercase tracking-wider text-muted-foreground">
            Topic / Chapter
          </label>
          <input
            value={topic}
            onChange={(e) => setTopic(e.target.value)}
            placeholder="e.g. Thermodynamics, Indian Polity..."
            className="mt-1 w-full rounded-xl bg-input/60 px-3 py-2.5 text-sm outline-none ring-1 ring-white/10 focus:ring-primary"
          />
        </div>

        <div className="grid grid-cols-2 gap-2">
          <div>
            <label className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Type
            </label>
            <select
              value={type}
              onChange={(e) => setType(e.target.value as typeof type)}
              className="mt-1 w-full rounded-xl bg-input/60 px-2 py-2.5 text-sm outline-none ring-1 ring-white/10 [color-scheme:dark]"
            >
              <option value="mcq">MCQ</option>
              <option value="short">Short</option>
              <option value="mixed">Mixed</option>
            </select>
          </div>
          <div>
            <label className="text-[10px] uppercase tracking-wider text-muted-foreground">
              Count: {count}
            </label>
            <input
              type="range"
              min={5}
              max={25}
              value={count}
              onChange={(e) => setCount(+e.target.value)}
              className="mt-2 w-full accent-[var(--primary)]"
            />
          </div>
        </div>

        <button
          onClick={generate}
          disabled={loading}
          className="flex w-full items-center justify-center gap-2 rounded-xl gradient-primary px-4 py-3 text-sm font-semibold shadow-[0_0_24px_-8px_var(--primary)] disabled:opacity-50"
        >
          {loading ? (
            <>
              <Loader2 size={16} className="animate-spin" /> Generating...
            </>
          ) : (
            <>
              <Sparkles size={16} /> Generate Mock Paper
            </>
          )}
        </button>
      </div>

      {paper && (
        <div className="space-y-3">
          <div className="glass rounded-2xl p-4">
            <div className="flex items-start justify-between gap-2">
              <div>
                <p className="font-display text-base font-semibold text-gradient">
                  {paper.title}
                </p>
                <p className="text-[11px] text-muted-foreground">
                  {paper.questions.length} questions
                </p>
              </div>
              <FileText className="text-accent" size={20} />
            </div>
            <div className="mt-3 flex gap-2">
              <button
                onClick={downloadPdf}
                className="flex flex-1 items-center justify-center gap-2 rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold"
              >
                <Download size={14} /> PDF
              </button>
              <button
                onClick={() => setShowAnswers((v) => !v)}
                className="flex-1 rounded-xl bg-white/10 px-3 py-2 text-xs font-semibold"
              >
                {showAnswers ? "Hide" : "Show"} Answers
              </button>
              <button
                onClick={() => {
                  add({
                    kind: "paper",
                    title: paper.title,
                    subtitle: `${paper.questions.length} questions`,
                    payload: paper as unknown as Record<string, unknown>,
                  });
                  toast.success("Saved");
                }}
                className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10"
                aria-label="Bookmark"
              >
                <Bookmark size={14} />
              </button>
            </div>
          </div>

          <ol className="space-y-2">
            {paper.questions.map((q, i) => (
              <li key={i} className="glass rounded-2xl p-3 text-sm">
                <p className="font-medium">
                  <span className="text-primary mr-1">Q{i + 1}.</span>
                  {q.question}
                </p>
                {q.options && (
                  <ul className="mt-2 space-y-1 text-xs">
                    {q.options.map((o, j) => (
                      <li key={j} className="rounded-lg bg-white/5 px-2.5 py-1.5">
                        <span className="font-semibold text-muted-foreground mr-2">
                          {String.fromCharCode(65 + j)}.
                        </span>
                        {o}
                      </li>
                    ))}
                  </ul>
                )}
                {showAnswers && (
                  <div className="mt-2 rounded-lg border border-emerald-500/20 bg-emerald-500/5 p-2 text-xs">
                    <p className="font-semibold text-emerald-300">
                      Ans: {q.answer}
                    </p>
                    {q.explanation && (
                      <p className="mt-1 text-muted-foreground">
                        {q.explanation}
                      </p>
                    )}
                  </div>
                )}
              </li>
            ))}
          </ol>
        </div>
      )}

      {!paper && !loading && (
        <p className="px-2 text-center text-[10px] text-muted-foreground">
          Topic + exam choose karke mock paper generate karo.
        </p>
      )}
    </div>
  );
}
